<p class="codepen" data-height="300" data-default-tab="html,result" data-slug-hash="bGzWYVP" data-user="Polina-Ostanina" style="height: 300px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;">
  <span>See the Pen <a href="https://codepen.io/Polina-Ostanina/pen/bGzWYVP">
  Pomodoro Timer</a> by Polina Ostanina (<a href="https://codepen.io/Polina-Ostanina">@Polina-Ostanina</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>
